# Site Info
title: FaeDine GameDev
tagline: 'FaeDine GameDev'
description: 'FaeDine GameDev'
baseurl: ""
url: http://www.faedine.com
logo: '/public/logo.png'

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss    
  
gems: [jekyll-paginate]
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty

version: 1.0.0

# About/contact
author:
  name: Kev Bourque
  description: Father, developer, fun maker. Occasionally all at the same time.
  gravatar: 85a8044f09fc1bd6ce7266aeaa8011f7 # md5 hash of your email address
  contact:
    linkedin:  https://ca.linkedin.com/in/kevbourque
    github:    https://github.com/faedine
    facebook:  http://facebook.com/faedine
    twitter:   https://twitter.com/faedine
    #weibo:     <hide>
    email:     mailto:faedine@gmail.com

# Navigation (2nd level links supported)
nav:
  Home:           
    - '/'
  Blog:           
    - '/blog/'
    - { Categories: '/blog/categories/' }
    - { Tags: '/blog/tags/' }
  Games:
    - '/games/'
  About:          
    - '/about/'
  Github Project: 
    - 'https://github.com/FaeDine/faedine.com-jekyll/'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

# Puglins
mathjax: true # whether support mathjax
google_analytics_token: 'UA-65728578-1' # leave blank if you don't want google analytics
disqus_short_name: '' # leave blank if you don't want disqus